package com.salad.cloud.imdssdk.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.With;
import lombok.extern.jackson.Jacksonized;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * An API error. The `code` and `type` uniquely identify the type of the error. The `code` is a short value that may be used for programmatic error handling. The `type` is an absolute URL that may be resolved for more detailed information. Refer to the [SaladCloud IMDS reference](https://leaf.salad.com/l/saladcloud-imds-errors) for a list of the expected `code` and `type` values. Also, note that all properties are optional. Clients should implement robust error handling to account for unexpected errors.
 */
@Data
@Builder
@With
@ToString
@EqualsAndHashCode
@Jacksonized
@NoArgsConstructor
@AllArgsConstructor
public class SaladCloudImdsError {

  /**
   * The error code that identifies the error type. This is a short value that may be used for programmatic error handling.
   */
  @JsonProperty("code")
  private JsonNullable<String> code;

  /**
   * The human-readable explanation specific to this occurrence of the error.
   */
  @JsonProperty("detail")
  private JsonNullable<String> detail;

  /**
   * The contextualized map of human-readable explanations specific to this occurrence of the error. This is often used to provide property-specific errors, such as validation errors. In these scenarios, the key is the property name and the value is an array of human-readable explanations specific to this property and this occurrence of the error.
   */
  @JsonProperty("errors")
  private JsonNullable<Map<String, List<String>>> errors;

  /**
   * The URI reference that identifies the specific occurrence of the error.
   */
  @JsonProperty("instance")
  private JsonNullable<String> instance;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the error.
   */
  @JsonProperty("status")
  private JsonNullable<Long> status;

  /**
   * The short, human-readable summary of the error type.
   */
  @JsonProperty("title")
  private JsonNullable<String> title;

  /**
   * The URI reference that identifies the error type.
   */
  @JsonProperty("type")
  private JsonNullable<String> type;

  @JsonIgnore
  public String getCode() {
    return code.orElse(null);
  }

  @JsonIgnore
  public String getDetail() {
    return detail.orElse(null);
  }

  @JsonIgnore
  public Map<String, List<String>> getErrors() {
    return errors.orElse(null);
  }

  @JsonIgnore
  public String getInstance() {
    return instance.orElse(null);
  }

  @JsonIgnore
  public Long getStatus() {
    return status.orElse(null);
  }

  @JsonIgnore
  public String getTitle() {
    return title.orElse(null);
  }

  @JsonIgnore
  public String getType() {
    return type.orElse(null);
  }

  // Overwrite lombok builder methods
  public static class SaladCloudImdsErrorBuilder {

    private JsonNullable<String> code = JsonNullable.undefined();

    @JsonProperty("code")
    public SaladCloudImdsErrorBuilder code(String value) {
      if (value == null) {
        throw new IllegalStateException("code cannot be null");
      }
      this.code = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> detail = JsonNullable.undefined();

    @JsonProperty("detail")
    public SaladCloudImdsErrorBuilder detail(String value) {
      if (value == null) {
        throw new IllegalStateException("detail cannot be null");
      }
      this.detail = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Map<String, List<String>>> errors = JsonNullable.undefined();

    @JsonProperty("errors")
    public SaladCloudImdsErrorBuilder errors(Map<String, List<String>> value) {
      if (value == null) {
        throw new IllegalStateException("errors cannot be null");
      }
      this.errors = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> instance = JsonNullable.undefined();

    @JsonProperty("instance")
    public SaladCloudImdsErrorBuilder instance(String value) {
      if (value == null) {
        throw new IllegalStateException("instance cannot be null");
      }
      this.instance = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<Long> status = JsonNullable.undefined();

    @JsonProperty("status")
    public SaladCloudImdsErrorBuilder status(Long value) {
      if (value == null) {
        throw new IllegalStateException("status cannot be null");
      }
      this.status = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> title = JsonNullable.undefined();

    @JsonProperty("title")
    public SaladCloudImdsErrorBuilder title(String value) {
      if (value == null) {
        throw new IllegalStateException("title cannot be null");
      }
      this.title = JsonNullable.of(value);
      return this;
    }

    private JsonNullable<String> type = JsonNullable.of("about:blank");

    @JsonProperty("type")
    public SaladCloudImdsErrorBuilder type(String value) {
      if (value == null) {
        throw new IllegalStateException("type cannot be null");
      }
      this.type = JsonNullable.of(value);
      return this;
    }
  }
}
